import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div class="grid min-h-screen place-items-center">
        <div class="w-11/12 p-12 bg-white sm:w-8/12 md:w-1/2 lg:w-5/12">
          <h1 class="text-xl font-semibold">
            Hello there 👋, 
            <span class="font-normal">
              please fill in your information to continue
            </span>
          </h1>
          <form class="mt-6">

            {/* First Name */}
            <label for="firstname" 
              class="block mt-2 text-xs font-semibold text-gray-600 uppercase">
                First Name
            </label>
            <input id="firstname" type="text" name="firstname" 
              placeholder="John" autocomplete="first-name" 
              class="block w-full p-3 mt-2 text-gray-700 bg-gray-200 
                appearance-none focus:outline-none focus:bg-gray-300 
                focus:shadow-inner" required />
            
            {/* Last Name */}
            <label for="lastname" 
              class="block mt-2 text-xs font-semibold text-gray-600 uppercase">
                Last Name
            </label>
            <input id="lastname" type="text" name="lastname" 
              placeholder="Doe" autocomplete="last-name" 
              class="block w-full p-3 mt-2 text-gray-700 bg-gray-200 
                appearance-none focus:outline-none focus:bg-gray-300 
                focus:shadow-inner" required />
            
            {/* Password */}
            <label for="password" 
              class="block mt-2 text-xs font-semibold text-gray-600 uppercase">
                Password
            </label>
            <input id="password" type="password" name="password" 
              placeholder="********" autocomplete="new-password" 
              class="block w-full p-3 mt-2 text-gray-700 bg-gray-200 
                appearance-none focus:outline-none focus:bg-gray-300 
                focus:shadow-inner" required />
            
            {/* Confirm Password */}
            <label for="password-confirm" 
              class="block mt-2 text-xs font-semibold text-gray-600 uppercase">
                Confirm password
            </label>
            <input id="password-confirm" type="password" 
              name="password-confirm" 
              placeholder="********" autocomplete="new-password" 
              class="block w-full p-3 mt-2 text-gray-700 bg-gray-200 
                appearance-none focus:outline-none focus:bg-gray-300 
                focus:shadow-inner" required />
            
            {/* Sign Up Button */}
            <button type="submit" class="w-full py-3 mt-6 font-medium 
              tracking-widest text-white uppercase bg-black shadow-lg 
              focus:outline-none hover:bg-gray-900 hover:shadow-none">
                Sign up
            </button>

            {/* Already Registed */}
            <p class="flex flex-start">
              <span class="flex justify-between inline-block mt-4 
                text-xs text-gray-500 m-1">
                  Already registered?
              </span> 
              <span class="flex justify-between inline-block mt-4 
                text-xs text-gray-500 cursor-pointer hover:text-black"> 
                  Log In
              </span>
            </p>
          </form>
        </div>
      </div>
    </div>
  )
}
